### ISSUE TITLE
Incorrect and missing data

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/entra-docs#117]
This note is wrong:
_You will get the <entityid> value from the Set up Tableau Cloud section in this tutorial. The entity ID value will be Microsoft Entra identifier value in Set up Tableau Cloud section._

There is no "Setup Tableau Cloud" section in the page. 
Secondly, there isn't anywhere on the page that it actually tells you how to get the ID

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbfa13a7-4d2d-b203-d7fa-760833a745cb
* Version Independent ID: 72ff67dc-732d-478e-1595-9d4bd6737714
* Content: [Tutorial: Microsoft Entra SSO integration with Tableau Cloud - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/tableauonline-tutorial#configure-azure-ad-sso)
* Content Source: [docs/identity/saas-apps/tableauonline-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/tableauonline-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by ManoharLakkoju-MSFT** [comment]
@danmyhre 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@danmyhre 

Thank you for bringing this to our attention. I apologize for any confusion caused by the incorrect note in the Azure documentation for configuring Azure AD SSO for Tableau Online.

To obtain the entity ID value for Tableau Online, you can follow these steps:

In the Azure portal, navigate to the Azure Active Directory service.
Click on "Enterprise applications" and select the Tableau Online application.
Click on "Single sign-on" and select "SAML".
Under "Basic SAML Configuration", copy the value of the "Entity ID" field.

Thank you for your feedback and please let me know if you have any further questions or concerns.
