### ISSUE TITLE
Unclear detail in Configure a custom signing key section

### ISSUE THREAD

**Issue by duplooysy** [MicrosoftDocs/entra-docs#119]
It is unclear from the [Configure a custom signing key section](https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization#configure-a-custom-signing-key) what type of certificate is required for the custom signing key, for example a server authentication certificate, client authentication certificate or both? Is a subject alternative name required in the certificate? If so, what should it be?

"Extract the private and public key base-64 encoded from the PFX file export of your certificate." From this it seems that the private key must be extracted, however the PowerShell script seems to Base-64 encode the entire .pfx file and not just the private key. This is very confusing. 

In the [example PATCH request](https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization#request), the Content-Type is servicePrincipals/json. This is incorrect. It should be application/json as the API does not accept servicePrincipals/json.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33741171-b5be-f59f-804a-a2fd252a399c
* Version Independent ID: c393e85e-a879-e98b-1a1a-cd4f85af6c42
* Content: [Customize app JSON Web Token (JWT) claims (Preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization)
* Content Source: [docs/identity-platform/jwt-claims-customization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/jwt-claims-customization.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by ManoharLakkoju-MSFT** [comment]
@duplooysy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@duplooysy 

Thank you for bringing this to my attention. I will do my best to clarify your questions.

Regarding the custom signing key, the type of certificate required is a code signing certificate. This certificate is used to sign the policy package before it is published. The certificate should be issued by a trusted certificate authority (CA) and should have the Code Signing Enhanced Key Usage (EKU) extension. The subject alternative name is not required in the certificate.

Regarding the PowerShell script, you are correct that the script Base-64 encodes the entire .pfx file, not just the private key. I apologize for the confusion. To extract the private and public key base-64 encoded from the PFX file export of your certificate, you can use the following PowerShell commands:

$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("path\to\certificate.pfx", "password")
$privateKey = [System.Convert]::ToBase64String($cert.PrivateKey.Export([System.Security.Cryptography.CryptoAPITypes]::PKCS8PrivateBlob))
$publicKey = [System.Convert]::ToBase64String($cert.PublicKey.Key.Export([System.Security.Cryptography.CryptoAPITypes]::X509SubjectPublicKeyInfo))

Regarding the example PATCH request, you are correct that the Content-Type should be application/json instead of servicePrincipals/json. Thank you for bringing this to my attention.

I hope this helps clarify your questions. Let me know if you have any further questions or concerns.
