### ISSUE TITLE
Need configuration dynamic redirect url 

### ISSUE THREAD

**Issue by SaibabaBalapur-MSFT** [MicrosoftDocs/entra-docs#157]
how to setup dynamic redirectURL in configuration for onedrive filepicker where as its only accepting static redirecturl? My site URL will be like [www.domain.com/abc/abc/123](http://www.domain.com/abc/abc/123) (everything changes dynamically after .com)

Can you guide Customer where and How they can add https://www.domain.com/*/ in azure portal?

-------------------------------
Document Details
⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

ID: 3f7ced07-0b71-715f-749b-180567591c72
Version Independent ID: 8c533d7b-a058-3f1a-c296-9c0305f85f13
Content: [Understanding the Microsoft Entra app manifest - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest?WT.mc_id=Portal-Microsoft_AAD_RegisteredApps)
Content Source: [docs/identity-platform/reference-app-manifest.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-app-manifest.md)
Service: active-directory
Sub-service: develop
GitHub Login: @rwike77 Ryan Wike FTE
Microsoft Alias: ryanwi

**Comment by SaibabaBalapur-MSFT** [comment]
@rwike77
Can you please check and add your comments on this query .

**Comment by bhahu** [comment]
@SaibabaBalapur-MSFT @rwike77 any updates?

**Comment by SaibabaBalapur-MSFT** [comment]
@rwike77 Please could you review it.

**Comment by rwike77** [comment]
Hi,  have you seen [this article](https://learn.microsoft.com//entra/identity-platform/reply-url#restrictions-on-wildcards-in-redirect-uris) that discusses wildcard character restrictions in reply/redirect URLs?

Looks like you can add wildcard characters in the portal app manifest editor for app registrations that sign in work or school accounts.  However we *strongly recommend* that you only use absolute URLS due to security implications.

If you're concerned you might exceed the [maximum number of redirect URIs](https://learn.microsoft.com/en-us/entra/identity-platform/reply-url#maximum-number-of-redirect-uris), you could try the state parameter approach.

Hope that helps.

**Comment by rwike77** [comment]
@SaibabaBalapur-MSFT I haven't heard back, I'll close this now.  I hope the info I provided was helpful.  Feel free to reopen if need be.  #please-close
