### ISSUE TITLE
Script not working / not explained

### ISSUE THREAD

**Issue by wolfgangbures** [MicrosoftDocs/entra-docs#162]
The New-MgApplicationTokenLifetimePolicyByRef  always throws exception Resource '......' does not
exist or one of its queried reference-property objects are not present.
Status: 404 (NotFound)
ErrorCode: Request_ResourceNotFound

I assume this should be the ApplicationID?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7537fd89-fd10-1fa2-a721-5260896cfa8a
* Version Independent ID: 8bacaf52-5b8b-d118-2bda-7dfc3861aaba
* Content: [Set lifetimes for tokens - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/configure-token-lifetimes)
* Content Source: [docs/identity-platform/configure-token-lifetimes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/configure-token-lifetimes.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by AjayBathini-MSFT** [comment]
@wolfgangbures 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@wolfgangbures 

Thank you for your question. Yes, the error message you are seeing when using the New-MgApplicationTokenLifetimePolicyByRef cmdlet is likely due to an incorrect Application ID.

When using this cmdlet, you need to provide the Application ID of the Azure AD application that you want to configure the token lifetime policy for. The Application ID should be a GUID that uniquely identifies the application.

Please ensure that you are providing the correct Application ID when using the New-MgApplicationTokenLifetimePolicyByRef cmdlet. You can find the Application ID in the Azure portal by navigating to the Azure AD application and looking for the "Application (client) ID" value.

I hope this helps. Let me know if you have any further questions or concerns.

**Comment by wolfgangbures** [comment]
Hello, and thank you for the reply. I am using the application-ID from the azure-portal, but still get the error!
I was able to create the policy, but cant assign it to the application. Is this maybe a wrong error message for a licensing issue? I am only running "Microsoft Entra ID Free"

________________________________

**Comment by AjayBathini-MSFT** [comment]
@wolfgangbures 

Microsoft Entra ID Free provides limited functionality compared to the paid versions of Microsoft Entra ID. It is possible that the ability to assign token lifetime policies to applications is not available in the free version.

For more clarification I'd recommend posting your question in https://azure.microsoft.com/en-us/support/community/. 
Thank you for your time and patience throughout this issue.
