### ISSUE TITLE
Ublock User Permissions

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/entra-docs#191]
What is the minimum RBAC role or Action for a custom role is required to give a helpdesk engineer access to unblock a user after they reported a Fraud? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84b26750-880c-8f14-1628-436293de915e
* Version Independent ID: 518b727f-79e8-b5c2-bcb3-ff4de3444c6f
* Content: [Configure Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-mfasettings)
* Content Source: [docs/identity/authentication/howto-mfa-mfasettings.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-mfasettings.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@Torxsmind 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Torxsmind 

The minimum RBAC role or action required for a helpdesk engineer to unblock a user after they reported a fraud would be the "Authentication administrator" role in Azure Active Directory. This role allows the user to manage Azure Multi-Factor Authentication settings, including unblocking users who have been blocked due to fraud or other security issues.
