### ISSUE TITLE
Incorrect instructios

### ISSUE THREAD

**Issue by teckalejandromacdonel** [MicrosoftDocs/entra-docs#203]
I wanted to review the lockout settings in Azure, and after PIMing up to Authentication Administrator, I wasn't able to see the settings as per the instructions. I logged out and logged back in to ensure that my account reported the correct roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7b90ca-a2b1-9cd8-9769-cd48c27f10ea
* Version Independent ID: b8c29389-c435-b2f0-4186-1e9c47ab4f3e
* Content: [Prevent attacks using smart lockout - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-smart-lockout)
* Content Source: [docs/identity/authentication/howto-password-smart-lockout.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-password-smart-lockout.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaibabaBalapur-MSFT** [comment]
@teckalejandromacdonel 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @teckalejandromacdonel 
It's possible that there may be some other issue preventing you from accessing the settings.

To troubleshoot this issue, I would recommend the following steps:

1. Check that you are signed in to the correct Azure AD tenant. Make sure that you are using the directory that contains your Azure AD tenant.
2. Verify that you have the correct permissions. In addition to being an Authentication Administrator, you may also need to be a Global Administrator or a Security Administrator to access the lockout settings.
3. Try accessing the lockout settings from a different browser or device to see if the issue is specific to your current environment.
4. Check the Azure AD audit logs to see if there are any errors or issues related to your account or the lockout settings.

If you are still unable to access the lockout settings after trying these steps, I would recommend reaching out to Microsoft support for further assistance. [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
