### ISSUE TITLE
I'm not a part of the organisation that I want to leave so I can't log in to leave the organisation that I'm no longer a part of so I can't ....

### ISSUE THREAD

**Issue by TheRealFlif** [MicrosoftDocs/entra-docs#211]
[Enter feedback here]
If I have left my organisation (i.e. I do not have an active account at the organisation), how can I log in using my account, that I don't have to leave the organisation which I'm no longer is a part of?

Feels like a catch 22

Best regards 
Stefan Cronert

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b448cfd0-b673-7d04-047b-71aa62bebc27
* Version Independent ID: 75118bff-94de-c9f9-7666-d2a6f4253b11
* Content: [Leave an organization as a guest user - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/leave-the-organization)
* Content Source: [docs/external-id/leave-the-organization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/leave-the-organization.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by SaibabaBalapur-MSFT** [comment]
@TheRealFlif 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
