### ISSUE TITLE
Changes made to AD remove all permissions from Zendesk

### ISSUE THREAD

**Issue by colehammock** [MicrosoftDocs/entra-docs#251]
This feature works great; however, any changes made to AD strip the user of their agent status and all embedded permissions within Zendesk... Anyone have any advice or workarounds for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe2af6f9-785f-8bcc-0afb-3e7398b1eb56
* Version Independent ID: e045f8bd-0ba2-27dd-1a23-3383b2463adf
* Content: [Tutorial: Configure Zendesk for automatic user provisioning with Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/zendesk-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/zendesk-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/zendesk-provisioning-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @twimmers
* Microsoft Alias: **Thwimmer**

**Comment by AjayBathini-MSFT** [comment]
@colehammock 

Based on the information you provided, it seems that any changes made to AD are causing the user to lose their agent status and permissions within Zendesk. This could be due to the fact that the Azure AD provisioning service is overwriting the user's permissions in Zendesk with the default permissions assigned during the provisioning process.

To avoid this issue, you can try assigning the user's permissions in Zendesk manually instead of relying on the automatic provisioning process. This will ensure that the user's permissions are not overwritten by the Azure AD provisioning service during any changes made to AD.

Another workaround could be to use the Zendesk API to automate the process of assigning permissions to users in Zendesk. This will allow you to have more control over the user's permissions and ensure that they are not overwritten during any changes made to AD.



I hope this helps! Let me know if you have any further questions or concerns.
