### ISSUE TITLE
Multiple forests (same NetBIOS / FQDN) to single Microsoft Entra tenant

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/entra-docs#254]
Hi everyone!
We are analyzing the merger of two companies into a single tenant. The particularity is that both AD Forests have the same NetBIOS name and FQDN. Is it a supported topology? Can I synchronize 2 different forests that have the same NetBIOS name / FQDN to a single tenant?

Thanks!
Fernando

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 755f7c4d-17cd-037d-22f6-a67f509bbed3
* Version Independent ID: 38908d84-c714-45d6-206a-b9d7da94aad0
* Content: [Microsoft Entra Connect: Supported topologies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/plan-connect-topologies#multiple-forests-single-microsoft-entra-tenant)
* Content Source: [docs/identity/hybrid/connect/plan-connect-topologies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/plan-connect-topologies.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Naveenommi-MSFT** [comment]
@FernandoGualano 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by FernandoGualano** [comment]
Hi @Naveenommi-MSFT 
Thanks for your answer!
The docs is https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/plan-connect-topologies#multiple-forests-single-microsoft-entra-tenant 

Thanks!
Fernando

**Comment by Naveenommi-MSFT** [comment]
@FernandoGualano 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@FernandoGualano 
Having two AD forests with the same NetBIOS name and FQDN is not a supported topology for Azure AD Connect. This is because Azure AD Connect uses the NetBIOS name and FQDN to identify the forest and domain during the synchronization process.

If you have two AD forests with the same NetBIOS name and FQDN, you will need to rename one of the forests to a unique name before you can synchronize both forests to a single Azure AD tenant.

Alternatively, you can consider using a third-party identity management solution that supports multiple forests with the same NetBIOS name and FQDN. However, this may require additional configuration and customization to ensure that the synchronization process works correctly.

I hope this helps! Let me know if you have any further questions or concerns.

**Comment by FernandoGualano** [comment]
Hi @AjayBathini-MSFT!
After your comment, I have a new question: Is it supported to rename an AD forest?

Thanks!
Fernando

**Comment by AjayBathini-MSFT** [comment]
@FernandoGualano 
Yes, it is possible to rename an Active Directory forest, but it is a complex process that requires careful planning and execution. Renaming an AD forest involves updating the forest root domain name, which can have significant impacts on the forest and its associated domains, applications, and services.

Microsoft provides detailed guidance on how to rename an Active Directory forest, including prerequisites, planning considerations, and step-by-step instructions. You can refer to the following documentation for more information:

https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/ad-ds-domain-rename

It is important to note that renaming an AD forest can have significant impacts on your environment.

**Comment by FernandoGualano** [comment]
Hi @AjayBathini-MSFT, 
Thannks for your answer! I try to browse the doc tha you send me but receive "404 - Page not found" error:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/50090959/078cc9bb-9fd0-486b-9b91-2685dd0f0e67)

Thanks!
Fernando

**Comment by AjayBathini-MSFT** [comment]
@FernandoGualano 

I apologize for the inconvenience. You can follow below steps.

Requirements for Domain Rename

Before a domain rename operation begins, the following requirements (but are not limited to) must be met:

1.The forest functional level must be Windows Server 2003 or higher.

2.If the position of domains will change, trust relationships must be created to provide trust between any domain that will be renamed (and therefore repositioned) and the domain that is to be its parent in the new structure.

3.DNS zones must exist for the new domains.

4.Domain-based Distributed File System (DFS) folder redirection paths must be redirected to a server-based path.

5.Domain-based roaming user profiles must be relocated to a server-based share or stand-alone DFS path.

6.Computers in the to-be-renamed domains must be configured to change their host names to reflect the new domain names.

7.Certification authority (CA) requirements must be met.

8.Location of the Domain – in forest it can have different level of domains. Those can be either complete different domains or child domains. If you going to change the location of the dc in the forest you must need to create trust relationships between domains to keep the connectivity.

9.DNS Zone – DNS Zone files must be created for the new domain name prior to the rename process in relevant DNS servers.

10.Computer Name Change – Once the domain is renamed the computers host names will also renamed. So if those are configured to use by applications or systems make sure you prepare to do those changes.

11.Once your infrastructure is ready, to perform the rename process we need an administrative computer or server. It must be a member of domain and should not a DC. It must have “Remote Server Administration Tools” installed.

12.Exchange Server Incompatibility

The domain rename operation is not supported in Microsoft Exchange 2000 server,Microsoft Exchange Server 2007 or Exchange Server 2010,Microsoft Exchange Server 2013.

DNS domain rename is supported in Exchange Server 2003 with Service Pack 1 (SP1). However, renaming of the NetBIOS domain name is not supported in any version of Exchange Server. Other non-Microsoft applications might also not support domain rename.

There are also non-Exchange applications that may be impacted, but Exchange is emphasized because email is often the most utilized form of communication and would be impacted most if you were to perform a domain rename. Also, renaming the NetBIOS domain name is not supported in any version of the Exchange Server. Lastly, keep in mind that non-Microsoft applications may also not support a domain rename.

If you perform an AD rename with an unsupported version of Exchange, you will need to create a new AD forest, install Exchange into the new forest, and migrate all the objects. However, this process is very time intensive and many not be realistic to undertake.

**Q1:**We have a running internal Certificate Server-probably even AD integrated--> How is this certainly recognizable?
A1:We can refer to the part of "CA Requirements" in the following link "How Domain Rename Works" and "Prepare Certification Authorities".

How Domain Rename Works

Prepare Certification Authorities

**Q2:**What's with the AD-integrated KMS licensing?
A2:I am sorry, after a lot of my research, I cannot find the affect on AD-integrated KMS licensing after domain rename.
We can consult our question by opening a new post and selecting Windows 10 general tags.

**Q3:**DFS is used --> What is there to consider?
A3:
1.Domain-based Distributed File System (DFS) folder redirection paths must be redirected to a server-based path.
2.Domain-based roaming user profiles must be relocated to a server-based share or stand-alone DFS path.
3.We can refer to the part of "Folder Redirection and Roaming User Profile Requirement" in the following link.

How Domain Rename Works

**Q4:**Microsoft 365 is operated from the local Active Directory with the help of AD Sync --> What is there to consider?
A4:We can consult our question by opening a new post and selecting Azure or O365 tags.

**Q5:**SQL Server work with Domain user -->What is there to adjust?
A5:We can consult our question by opening a new post and selecting SQL tags.

**Q6:**What does the rename mean for the SCCM?
A6:We can consult our question by opening a new post and selecting SCCM tags.

**Q7:**Which causes does the rename have for f.e. helpingtools such as NetFX?
A7:You can use the domain rename process to change the names of your domains, and you can also use it to change the structure of the domain trees in your forest. This process involves updating the Domain Name System (DNS) and trust infrastructures as well as Group Policy and service principal names (SPNs).

The ability to rename domains provides you with the flexibility to make important name changes and forest structural changes as the needs of your organization change. Using domain rename, you cannot only change the name of a domain, but you can change the structure of the domain hierarchy and change the parent of a domain or move a domain residing in one domain tree to another domain tree. The domain rename process can accommodate scenarios involving acquisitions, mergers, or name changes in your organization, but it is not designed to accommodate forest mergers or the movement of domains between forests.

**Q8:**What does the rename mean for 802.1x authentification in the WLAN?
A8:We can consult our question by opening a new post and selecting Network or WLAN or 802.1x authentification tags.

**Q9:**What about the changes to vSphere and VEEAM?
A9:We can ask engineers of vSphere and VEEAM for help.

**Q10:**How does a print server actually react to the name change?
A10:We can consult our question by opening a new post and selecting printer tags.

It seems your AD environment is more complex, it is recommended you would probably just create a new domain, and move or migrate everything to new domain using ADMT tool if needed.

Hope the information above is helpful.

**Comment by AjayBathini-MSFT** [comment]
@FernandoGualano 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
