### ISSUE TITLE
Missing Step - Grant Admin Consent for Default Directory

### ISSUE THREAD

**Issue by AlexLovelock22** [MicrosoftDocs/entra-docs#258]
I'm not a great programmer, so I don't really know what the cause and what the fix is - but I have something which works now lol.

I was logging in and I was either infinitely looping around something, or getting a "we couldnt sign you in"

Two things to note :

**1)** Under "API Premissions", under "Configured Permissions" you need to click "Grant Admin Consent for Default Directory", I think this enables some kind of User.Read permission or something? Either way - that might be what fixed it. 

**2)** Be vigilant of the error messages saying something like :

User
AADSTS50011: The redirect URI 'https://localhost:7016/signin-oidc' specified in the request does not match the redirect URIs configured for the application 'ID HERE'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Sometimes I found removing the S in HTTPS, or readding it I can't remember in the EntraID RedirectURI's section would also fix it. 

Sorry I don't really know the specifics, but good luck! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d460a936-67c4-7d18-7003-38dcc133d43d
* Version Independent ID: d460a936-67c4-7d18-7003-38dcc133d43d
* Content: [Tutorial: Call an API and display the results - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-app-dotnet-call-api?tabs=visual-studio%2Cdotnet6)
* Content Source: [docs/identity-platform/tutorial-web-app-dotnet-call-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-web-app-dotnet-call-api.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@AlexLovelock22 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@AlexLovelock22 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by cilwerner** [comment]
Hi @AlexLovelock22, just a note for the future that when dealing with apps like this to always use `https` which means that the website is "secure", otherwise it defeats the purpose for securing an application. As for the error, you'd usually get it when the redirect URI in the admin center and your application do not match.

Can you try going to the *Properties/launchSettings.json* file in your application and navigate to the `https` section (usually around line 21 for .NET 7.0). You'll see,

`"applicationUrl": "https://localhost:{port1};http://localhost:{port2}",`

The `https://localhost:{port1}` should directly match the value you put for the redirect URI in the admin center..

**Comment by AlexLovelock22** [comment]
Hey! @cilwerner Thanks for the reply, and apologies for delay in response - I can confirm we have now done that, thank you.
