### ISSUE TITLE
Page Could Use Better Examples for  Configuring the Downstream API

### ISSUE THREAD

**Issue by Alfetta159** [MicrosoftDocs/entra-docs#311]
In the section:

### Option 2: Call a downstream web API other than Microsoft Graph

... the following code is shown w/ configuration from "MyApiScope". There isn't a clear example of what that JSON should look like, nor is it clear what "MyApi" should be, a Client ID?

```
using Microsoft.Identity.Web;

// ...
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(Configuration, "AzureAd")
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddDownstreamApi("MyApi", Configuration.GetSection("MyApiScope"))
    .AddInMemoryTokenCaches();
// ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc5b4a3-0d85-102b-8b4c-8dfdd664b2d8
* Version Independent ID: 13086ddd-1cf0-a8ca-46f2-588e59734122
* Content: [Configure a web API that calls web APIs - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-api-call-api-app-configuration?tabs=aspnetcore)
* Content Source: [docs/identity-platform/scenario-web-api-call-api-app-configuration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-web-api-call-api-app-configuration.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@Alfetta159 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Alfetta159 The AddDownstreamApi method configures the downstream web API for use with the EnableTokenAcquisitionToCallDownstreamApi method. This setup allows your web API to obtain tokens required to call the downstream web API on behalf of the user.

In this scenario, "MyApi" denotes the name of the downstream web API that your web API intends to call. "MyApiScope" represents the scope necessary for your web API to request in order to interact with the downstream web API.

The JSON configuration for "MyApiScope" should encompass essential information for your web API to authenticate and authorize with the downstream web API. This might include details like the client ID, client secret, and authorization endpoint for the downstream web API.

I hope this explanation clarifies things for you! Let me know if there are any further questions.

**Comment by SaibabaBalapur-MSFT** [comment]
@Alfetta159 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Alfetta159** [comment]
Did you update the webpage in question? That's what this issue is about. I was able to figure out what needed to be done, but this issue is that the documentation is poorly written and should be updated. Unless you recommend that I fork that myself.

**Comment by SaibabaBalapur-MSFT** [comment]
@cilwerner
Can you please check and add your comments on this doc update request as applicable.

**Comment by cilwerner** [comment]
#please-close

**Comment by MarekLani** [comment]
Documentation is still absolutely poor. No idea how the appsettings should liik like if using .AddDownstreamApi("MyApi", Configuration.GetSection("MyApiScope")). Also the next page in the flow is absolutely not demonstrating the purpose of using .AddDownstreamApi("MyApi", Configuration.GetSection("MyApiScope"))
