### ISSUE TITLE
msidentity-app-sync doesn't work when .NET 5 isn't installed.

### ISSUE THREAD

**Issue by mikegoatly** [MicrosoftDocs/entra-docs#336]
I followed the instructions and got to "Use the Microsoft Identity App Sync Tool". After trying to run `msidentity-app-sync` as described, I get the error:

```
You must install or update .NET to run this application.

App: C:\Users\MikeGoatly\.dotnet\tools\msidentity-app-sync.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  6.0.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win-x64&os=win10
```

The version of `msidentity-app-sync` that I get when running `dotnet tool install` is v1.0.1:

```
❯ dotnet tool install --global msidentity-app-sync
Skipping NuGet package signature verification.
You can invoke the tool using the following command: msidentity-app-sync
Tool 'msidentity-app-sync' (version '1.0.1') was successfully installed.
```

So it looks like either the tool needs to be updated, or the documentation needs to change to have an alternative approach to configuring the application in Microsoft Entra.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1279b6d-8210-1751-8e37-cf544cd3695d
* Version Independent ID: 6dc2d359-8d50-1df3-7983-29fb06bfdbb6
* Content: [Tutorial - Create a Blazor Server app that uses the Microsoft identity platform for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server)
* Content Source: [docs/identity-platform/tutorial-blazor-server.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-blazor-server.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by ManoharLakkoju-MSFT** [comment]
@mikegoatly 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@mikegoatly
I've delegated this to @henrymbuguakiarie, a content author, to review and share their valuable insights.

**Comment by JoshElias** [comment]
I've been waiting for this guide to be updated for a while now. I used to get the same error as OP but now with .NET 8 it can't find my install SDKs at all. I have set DOTNET_ROOT appropriately, `home/josh/.dotnet`

I get the following output from `dotnet --list-sdks`
```
5.0.408 [/home/josh/.dotnet/sdk]
7.0.406 [/home/josh/.dotnet/sdk]
8.0.200 [/home/josh/.dotnet/sdk]
```

And the following from `dotnet --list-runtimes`
```
Microsoft.AspNetCore.App 5.0.17 [/home/josh/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.16 [/home/josh/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.2 [/home/josh/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.17 [/home/josh/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.16 [/home/josh/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.2 [/home/josh/.dotnet/shared/Microsoft.NETCore.App]
```

**Comment by aitrailblazer** [comment]
Same here, are there are instructions how to recompile the source code with .NET 8.0?

**Comment by Pat-HS** [comment]
Same issues here.  Any updates on when this will be corrected and available?  Or at least a guide to manually set this up as necessary?

**Comment by henrymbuguakiarie** [comment]
Hello @mikegoatly,

After reviewing the current tutorial, we decided to retire it for the following reason:

- The msidentity-app-sync tool fails to work without .NET 5 installed, and .[NET 5 is no longer supported](https://dotnet.microsoft.com/en-us/platform/support/policy).
- The tutorial uses the blazorserver template to scaffold the code, including calls to Microsoft Graph. However, [.NET 8 discontinued the blazorserver](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#blazorserver).
- The tutorial is based on .NET 7, which is no longer supported.

.NET 8 has a [New Blazor Web App template](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#new-blazor-web-app-template) which  combines the strengths of the existing Blazor Server and Blazor WebAssembly hosting models with the new Blazor capabilities added in .NET 8.

**Solution**

- We need a new tutorial using the [New Blazor Web App template](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#new-blazor-web-app-template). An internal work item will track this, but we have no timeline due to other priorities.

Cc: @ManoharLakkoju-MSFT @RamanathanChinnappan-MSFT @JoshElias @Pat-HS @aitrailblazer
