### ISSUE TITLE
Delegating permission to MSA

### ISSUE THREAD

**Issue by BillyA7** [MicrosoftDocs/entra-docs#342]
I have a script that automatically rolls over the Kerberos decryption key of the AZUREADSSO computer account every 30 days.
 
At the moment it uses an AD user service account with delegated permissions of write and reset password for the AZUREADSSO computer account.
 
I would like to be able to run the following command using a MSA to improve security so I don't have to manage the AD user service account.

Update-AzureADSSOForest -OnPremCredentials $creds -PreserveCustomPermissionsOnDesktopSsoAccount

It seems the -OnPremCredentials parameter is mandatory and it will not accept a null password when trying to use the MSA.

Is what I'm trying to achieve possible at all?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f01328-ebfa-31af-4e67-6de92c8f924e
* Version Independent ID: a990551f-e6c9-dede-308a-b5578fb7ee1e
* Content: [Microsoft Entra Connect - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sso-faq#how-can-i-roll-over-the-kerberos-decryption-key-of-the--azureadsso--computer-account-)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sso-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sso-faq.yml)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Naveenommi-MSFT** [comment]
@BillyA7 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by BillyA7** [comment]
Apologies for that @Naveenommi-MSFT, the link to the documentation:

https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sso-faq#how-can-i-roll-over-the-kerberos-decryption-key-of-the--azureadsso--computer-account-

Thanks

**Comment by Naveenommi-MSFT** [comment]
@BillyA7 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @BillyA7 
Regrettably, utilizing a Managed Service Account (MSA) with the `Update-AzureADSSOForest` command is not feasible. The `-OnPremCredentials` parameter necessitates a username and password for authentication with the on-premises Active Directory domain controller. However, MSAs lack passwords that can be utilized for authentication.

As an alternative, you could consider using a Group Managed Service Account (gMSA) instead of an AD user service account. gMSAs are a type of Active Directory account that can be used as service accounts and have their passwords managed automatically by Active Directory. This would eliminate the need to manage the password for the service account used to roll over the `Kerberos` decryption key.

Another option is to consider employing a certificate-based authentication method for Azure AD Seamless Single Sign-On (Azure AD Seamless SSO) instead of `Kerberos`. This approach would eradicate the necessity to roll over the `Kerberos` decryption key entirely, offering a more secure authentication method.

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@BillyA7 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
