### ISSUE TITLE
Release notes for 2.3.6 missing

### ISSUE THREAD

**Issue by martinjp84** [MicrosoftDocs/entra-docs#413]
App upgraded to 2.3.6 automatically, no release notes available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd856307-25bf-4b18-ef90-75df56fd9493
* Version Independent ID: 59686ac8-db3d-0edf-ba0e-4aef1e2fdd0b
* Content: [Microsoft Entra Connect: Version release history - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-version-history)
* Content Source: [docs/identity/hybrid/connect/reference-connect-version-history.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/reference-connect-version-history.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Fero-0** [comment]
Our monitoring system reports missing services. It seems that this update REMOVES the services "Azure AD Connect Health Sync Insights" and "Azure AD Connect Health Sync Monitoring" and replaces them through this new? service "AzureADCibbectHealthAgent". 

Now I don't know if they are REALLY SUPPOSED TO BE removed or something went rouge during the update, since there is no changelog. This is really not a good way to push updates...

**Comment by AjayBathini-MSFT** [comment]
@martinjp84 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by billmath** [comment]
@martinjp84 Thank you for the feedback.  We are aware of this and they should be live shortly.  Thanks!

#please-close

**Comment by martinjp84** [comment]
You've created the release notes but they are incomplete. As @Fero-0 mentioned, two services are deleted and are replaced by a new Entra health monitoring service.
