### ISSUE TITLE
Licensing Fundamentals - Entra ID Governance & Workflows

### ISSUE THREAD

**Issue by GinoBarletta** [MicrosoftDocs/entra-docs#418]
In the examples provided within this 'licensing fundamentals' specifically with the 'Workflows' example of both onboarding and offboarding users, I understand that 'Entra ID Governance' licenses are required to be assigned to specific users which are part of the lifecycle's workflow.
Clarification: When offboarding users, the above license must be assigned before the workflow can be executed. Then as part of the workflow, the identity is deleted, thus reducing the total user count.

To me, it seems a bit strange to assign an expensive 'Entra ID Governance' license to a user, to execute an offboarding workflow, which is about to be deleted from the Entra ID directory.

Is this correct, or am I missing something fundamental here ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c48d98ed-5170-140d-59cc-344c755311cc
* Version Independent ID: 0ace47ad-ae37-5b99-0bc0-63f0d05f8ed6
* Content: [Microsoft Entra ID Governance licensing fundamentals - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/licensing-fundamentals)
* Content Source: [docs/id-governance/licensing-fundamentals.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/licensing-fundamentals.md)
* Service: **entra-id-governance**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@GinoBarletta 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @GinoBarletta 
You are correct that Entra ID Governance licenses are required for users who are part of the onboarding and offboarding workflows. However, it is not necessary to assign an Entra ID Governance license to a user who is about to be deleted from the Entra ID directory.

When a user is offboarded, their identity is removed from the Entra ID directory, but the license assignment remains in place until it is manually removed. This is because the license assignment is tied to the user's identity at the time of assignment, not their current status in the directory.

So, while it may seem strange to assign an expensive license to a user who is about to be deleted, it is necessary to have the license assigned during the offboarding workflow to ensure that the appropriate governance controls are in place and that the user's access is properly managed before their identity is removed from the directory.

I hope this clarifies any confusion you may have had. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by GinoBarletta** [comment]
Thank you for the clarification.
It would be good to provide an example in the document that outlines this, to provide better clarification.
🙂

Gino Barletta | Mobile: 0412.116.837 | email: ***@***.******@***.***>
________________________________

**Comment by Naveenommi-MSFT** [comment]
@GinoBarletta 
We will contact our PG team to thoroughly investigate the matter and provide updates as necessary.
Now we are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
