### ISSUE TITLE
Just a though - unsuccessful sign-ins might be bad to capture in lastSignInDateTime

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/entra-docs#441]
I was just stung (zero pain) by the fact that lastSignInDateTime is updated even upon an unsuccessful sign-in.  I know this page is just for documentation and GitHub issues on Learn pages is going away altogether.  nonetheless, leaving this here.

How can one section on the page state to use this property for the purpose of identifying inactive users, when the property might show a recent sign-in event, however that sign-in event might not even have been successful (e.g., Password Spray, popular as all get out)?

To me it makes sense to only capture successful sign-ins, or at least for the signInActivity resource to include success/failure results of that last recorded attempt.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0a0671-953a-7797-6e0c-6616420f4c3b
* Version Independent ID: a2de95d1-67b2-bcc6-402f-f5d23c53d13a
* Content: [How to manage inactive user accounts - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/howto-manage-inactive-user-accounts)
* Content Source: [docs/identity/monitoring-health/howto-manage-inactive-user-accounts.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/monitoring-health/howto-manage-inactive-user-accounts.md)
* Service: **entra-id**
* Sub-service: **monitoring-health**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by RamanathanChinnappan-MSFT** [comment]
@JeremyTBradshaw
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by shlipsey3** [comment]
Hi @JeremyTBradshaw - the lastSignInDateTime and SignInActivity do capture sign-in _attempts_, but it's important to show failed and successful attempts. Because it's difficult to parse out with one property, the team has been working on additional properties that are just for successful attempts. These are in beta, so aren't recommended for production environments. We're starting to introduce them into documentation where appropriate. 

https://learn.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta

Please continue to check the API documentation - v1.0 and beta - for the latest properties that you can filter by. I hope that helps.

As for feedback - continue using GitHub as long as you can. And you'll still be able to submit changes to public docs, if you encounter anything that needs to be updated. The new feedback tool we're working with will have a different experience, but will get new features as it matures. Let me know if there's anything else I can help with.

**Comment by JeremyTBradshaw** [comment]
@shlipsey3 thanks very much.  I see the lastSuccessfulSignInDateTime property mentioned in the beta link you shared.  That's awesome and exactly what I need.  Thanks and thanks.  I will keep an eye on that, as I did back in the days of anticipating signInActivity's eventual GA.  Exciting to see this is already on the way.

**Comment by shlipsey3** [comment]
Fantastic! 
I'm working on adding the "successful" option to the docs - just need to test it and make sure the beta language is good to go. Thanks for submitting feedback!

#please-close

**Comment by JeremyTBradshaw** [comment]
Hi @shlipsey3 - I wonder if you could help me with something?  No pressure but just would like a 2nd opinion.  Here's what we have today in our inactive accounts script:

```powershell
# Add the AADLastSignIn using the newer of lastSignInDateTime or lastNonInteractiveSignInDateTime:
$thisUser['AADLastSignIn'] = if ($mgU.signInActivity) {
    ($mgU.signInActivity.lastSignInDateTime, $mgU.signInActivity.lastNonInteractiveSignInDateTime |
    Sort-Object | Select-Object -Last 1) -as [datetime]
}
else { $null }
```
As you can see, we take the more recent of either lastSignInDateTime or lastNonInteractiveSignInDateTime.  The question I have is - is lastNonInteractiveSignInDateTime also potentially showing failed attempts?  Or should I take the same approach and get the newer of either lastSuccessfulSignInDateTime (via Beta) and/or lastNonInteractiveSignInDateTime?

Our inactivity threshold is 60 days and I know refresh tokens can last longer than that, so I just am trying to avoid missing legit activity captured via the non-interactive sign-ins.  But if there's a chance that property is including failed sign-in attempts, I'd forget about it and we'll strictly go off of lastSuccessful.

Thanks in advance.

**Comment by shlipsey3** [comment]
It's all good - sometimes you need a second pair of eyes while you work through the question. I've totally been there. ;)
