### ISSUE TITLE
SCIM endpoint development - Outdated information on trusted certificate authorities

### ISSUE THREAD

**Issue by busch** [MicrosoftDocs/entra-docs#461]
Hey Microsoft,

According to the docs, the SCIM endpoint must have a webserver authentication certificate signed by "DST Root CA X3", which expired in 2021: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
Current chain of trust is "ISRG Root X1" for RSA and "ISRG Root X2" for ECDSA certificates: https://letsencrypt.org/certificates/

Not sure if this is just outdated information in the docs or a real issue in the product, as my SCIM endpoint details cannot be fetched using https://scimvalidator.microsoft.com/ from an endpoint that is using a certificate signed by "ISRG Root X1".

Best regards,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 271dc426-fb47-7441-d627-ec11f8c7a6ea
* Version Independent ID: 4cb8bfc8-4748-e501-425a-e4c2da0f5f5a
* Content: [Tutorial - Develop a SCIM endpoint for user provisioning to apps from Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups)
* Content Source: [docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@busch
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@busch The DST Root CA X3 certificate has expired in 2021 and the current chain of trust is ISRG Root X1 for RSA and ISRG Root X2 for ECDSA certificates. Therefore, it is recommended to use the current chain of trust for your certificates.

Regarding the issue you are facing with the SCIM endpoint details not being fetched using https://scimvalidator.microsoft.com/, it is possible that the validator is not updated to recognize the new chain of trust. You can try using other validators or contact Microsoft support for further assistance [support ticket](https://azure.microsoft.com/support/create-ticket/) since the support team will be able to respond much more quickly and have a conversation with you to figure out what could be going on.

**Comment by SaibabaBalapur-MSFT** [comment]
@busch 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
