### ISSUE TITLE
What happens after a reviewer concludes a review? Right now they keep getting notifications to do the review, even after completing them.

### ISSUE THREAD

**Issue by MarcellusMo** [MicrosoftDocs/entra-docs#495]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60590ca9-3b4d-925b-4d01-b7c40b02416e
* Version Independent ID: 9b25c948-12b8-331b-1661-485dceb148a2
* Content: [Review access to groups & applications in access reviews - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/perform-access-review)
* Content Source: [docs/id-governance/perform-access-review.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/perform-access-review.md)
* Service: **entra-id-governance**
* Sub-service: **access-reviews**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by ManoharLakkoju-MSFT** [comment]
@MarcellusMo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@MarcellusMo 
After a reviewer concludes a review, they should no longer receive notifications to do the review. If a reviewer is still receiving notifications after completing a review, it could be due to a few reasons:

1. The access review is set to recur at a certain interval, and the reviewer has been assigned to the next review cycle. In this case, the reviewer will receive a notification for the next review cycle.

2. The reviewer has not completed all of their assigned reviews. In this case, the reviewer will continue to receive notifications until they have completed all of their assigned reviews.

3. There is a delay in the system updating the review status. In this case, the reviewer should stop receiving notifications after a short delay.

If the reviewer is still receiving notifications after completing all of their assigned reviews and there is no delay in the system updating the review status, it could be a bug or an issue with the configuration of the access review. In this case, you should contact Microsoft support for further assistance.

I hope this helps! Let me know if you have any further questions.

**Comment by MarcellusMo** [comment]
Thanks for your clear answer. 
I'll keep an eye on it, but it seems that until the due date in two weeks, the reviews stay pending, although they have been confirmed already.
