### ISSUE TITLE
read and handle  the exception inside msal controlled Popup

### ISSUE THREAD

**Issue by shivamjadhav2000** [MicrosoftDocs/entra-docs#503]
how to read the error for tenant AADSTS50020: User account 'user@gmail.com' 
and show this error in a react app.
i have an react app configured with the msal here if i use a user who is not in my tenant and does login we get an exception i want to have an ability to control this state and show this error in react app instead in the msal contorlled popup window.

**Comment by ManoharLakkoju-MSFT** [comment]
@shivamjadhav2000 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by shivamjadhav2000** [comment]
@ManoharLakkoju-MSFT this isn't the issue with the documentation , i have read the documentation and configured my react app with the msal and everything works fine [documentationLink](https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-react-spa-app
![tenant exception]
 , my app uses tenant id and only lets user under my tenant to signin other wise it shows the exception in the popup/
![tenant exception](https://github.com/MicrosoftDocs/entra-docs/assets/52875456/97e57f2f-c372-4139-a49e-f865b13409ec)
redirected page

**Comment by ManoharLakkoju-MSFT** [comment]
@shivamjadhav2000 
Thank you for your feedback!

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
