### ISSUE TITLE
BrowerConfigurationAuth Error

### ISSUE THREAD

**Issue by mirojs** [MicrosoftDocs/entra-docs#510]
[Enter feedback here]

Hello,

After following pretty every individual step and got the following error:

BrowserConfigurationAuthError: stubbed_public_client_application_called: Stub instance of Public Client Application was called. If using msal-react, please ensure context is not used without a provider.

Please try to help, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bcf5209-d3df-11ea-64b7-0521f33a2348
* Version Independent ID: 9ca03d8c-2eaa-5cdd-e63a-dbbe0ad04430
* Content: [Tutorial: Add sign-in and sign-out to a React SPA for a customer tenant - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-react-sign-in-sign-out)
* Content Source: [docs/external-id/customers/tutorial-single-page-app-react-sign-in-sign-out.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-single-page-app-react-sign-in-sign-out.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @godonnell
* Microsoft Alias: **godonnell**

**Comment by RamanathanChinnappan-MSFT** [comment]
@mirojs 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.



[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1

**Comment by mirojs** [comment]
@RamanathanChinnappan-MSFT After contacting with the Azure support, they expected someone from Github to help solving the issue due to the origin of the code. May I know if the Gitthub code had been fully tested to be 100% workable? Thanks.
