### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Expecho** [MicrosoftDocs/entra-docs#554]
So I am trying to create a new blazor server project with authentication set to multiple organizations. Apparently this is no longer possible using a `dotnet new` template. So the line `dotnet new blazorserver --auth SingleOrg --calls-graph` is no longer valid for .Net 8 project. We are supposed to use `dotnet new blazor` but that cannot deal with organization / entra Id accounts, see [the docs](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#blazor):

![image](https://github.com/MicrosoftDocs/entra-docs/assets/11960665/914b3284-60a3-4db5-90d2-103584f8d49c)

So this doc is no longer providing any value or needs some updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1279b6d-8210-1751-8e37-cf544cd3695d
* Version Independent ID: 6dc2d359-8d50-1df3-7983-29fb06bfdbb6
* Content: [Tutorial - Create a Blazor Server app that uses the Microsoft identity platform for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server)
* Content Source: [docs/identity-platform/tutorial-blazor-server.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-blazor-server.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by Naveenommi-MSFT** [comment]
@Expecho 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Expecho 
Thank you for bringing this to our attention.
I've delegated this to content author @henrymbuguakiarie, who will review it and offer their insightful opinions.

**Comment by jongio** [comment]
I also ran into issues with this and it needs to be upgraded to the latest .NET 8 blazor model.  @henrymbuguakiarie are we working on updating this?

**Comment by henrymbuguakiarie** [comment]
Hello @Expecho,

Thank you for reaching out and contributing to our documentation. I've queued this for update by the end of May since .NET 7 end of support is May 14, 2024.

Cc: @jongio

**Comment by jongio** [comment]
Can you get a draft going so we can test it out?  Thanks

**Comment by henrymbuguakiarie** [comment]
Hello @Expecho,

After reviewing the current tutorial, we decided to retire it for the following reason:

- The msidentity-app-sync tool fails to work without .NET 5 installed, and .[NET 5 is no longer supported](https://dotnet.microsoft.com/en-us/platform/support/policy).
- The tutorial uses the blazorserver template to scaffold the code, including calls to Microsoft Graph. However, [.NET 8 discontinued the blazorserver](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#blazorserver).
- The tutorial is based on .NET 7, which is no longer supported.

.NET 8 has a [New Blazor Web App template](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#new-blazor-web-app-template) which  combines the strengths of the existing Blazor Server and Blazor WebAssembly hosting models with the new Blazor capabilities added in .NET 8.

**Solution**

- We need a new tutorial using the [New Blazor Web App template](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#new-blazor-web-app-template). An internal work item will track this, but we have no timeline due to other priorities.

Cc: @ManoharLakkoju-MSFT @jongio

**Comment by mkArtakMSFT** [comment]
@jennyf19 , @jmprieur , @JeremyLikness , @halter73 FYI, as this is related to a conversation we had about a month ago.
