### ISSUE TITLE
Add "OneNote" under "Microsoft Teams" - CA Policy

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/entra-docs#558]
**In Policy enforcement**
Please verify if the Application "OneNote" also should be under "Microsoft Teams".
This is the new "Wiki" App inside of Teams, which is now called "Notes".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7834fc25-6e4d-1a00-e9d3-949928ccb94b
* Version Independent ID: 23e71a83-28ea-da6f-0e3e-cda56a320358
* Content: [Conditional Access service dependencies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/service-dependencies)
* Content Source: [docs/identity/conditional-access/service-dependencies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/service-dependencies.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@weyCC81 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@weyCC81 
I've delegated this to @MicrosoftGuyJFlo, a content author, to review and share their valuable insights.

**Comment by MicrosoftGuyJFlo** [comment]
The list is not exhaustive and is just a representation since new apps are added all the time. We recommend targeting all of the Office apps with the Office 365 app grouping to avoid dependency issues. 

You can see what resources are called by following the guidance in the referenced troubleshooting doc. https://learn.microsoft.com/entra/identity/conditional-access/troubleshoot-conditional-access#service-dependencies

#please-close

**Comment by weyCC81** [comment]
Okay, that is unfortunate. So I can not prove this to the customer then. Would be nice for planning phases to have the right Information in the docs.
