### ISSUE TITLE
Powershell commands do not work - set up groups for sensitivity labels

### ISSUE THREAD

**Issue by Mad-Sabre** [MicrosoftDocs/entra-docs#593]
I followed the PowerShell commands to turn on groups for sensitivity labels, and always came back saying,

Update-MgBetaDirectorySetting : Cannot process argument transformation on parameter 'DirectorySettingId'. Cannot convert value to type System.String.
At line:11 char:51
+ ... etaDirectorySetting -DirectorySettingId $grpUnifiedSetting.ID -BodyPa ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-MgBetaDirectorySetting], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Update-MgBetaDirectorySetting
 
I looked into this, and the search does not pull the ID for Group.Unified, but all the IDs
changing the command to this came back with out errors.

$grpUnifiedSetting = (Get-MgBetaDirectorySetting |  where { $_.DisplayName -eq "Group.Unified" })

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef84a3e0-879e-4312-a89d-7a3bb0cd9a51
* Version Independent ID: 43851f8a-b71f-0a0a-8b1f-629e3528972f
* Content: [Assign sensitivity labels to groups - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-assign-sensitivity-labels)
* Content Source: [docs/identity/users/groups-assign-sensitivity-labels.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-assign-sensitivity-labels.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@Mad-Sabre 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @Mad-Sabre
It seems that you are encountering an error when running the `Update-MgBetaDirectorySetting` command to enable sensitivity labels for groups in Azure AD. The error message indicates that the `DirectorySettingId` parameter cannot be converted to a string.

One possible reason for this error is that the `ID` property of the `$grpUnifiedSetting` object is not a string. To fix this, you can try changing the command to use the `ObjectId` property of the `$grpUnifiedSetting` object instead of the `ID` property, like this:

```
Update-MgBetaDirectorySetting -DirectorySettingId $grpUnifiedSetting.ObjectId -BodyParameter $Setting
```

Alternatively, you can try using the `DirectorySetting` parameter instead of the `DirectorySettingId` parameter, like this:

```
Update-MgBetaDirectorySetting -DirectorySetting $grpUnifiedSetting -BodyParameter $Setting
```

I hope this helps! If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@Mad-Sabre 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
