### ISSUE TITLE
Is this feature available in Azure Gov? 

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/entra-docs#60]
Is Dynamic memberships available in Azure Gov/GCCH? 

Is there any known limitations in Azure Gov/ GCCH? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72bf3d35-e81f-adae-e9ae-c0dfa5dc4848
* Version Independent ID: 499bd02d-e05c-1ada-1541-efa0075ae205
* Content: [Manage users or devices for an administrative unit with dynamic membership rules (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/admin-units-members-dynamic)
* Content Source: [docs/identity/role-based-access-control/admin-units-members-dynamic.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/admin-units-members-dynamic.md)
* Service: **active-directory**
* Sub-service: **roles**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by SaibabaBalapur-MSFT** [comment]
@J227668 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @J227668 
Dynamic memberships for administrative units are available in Azure Government and Azure Government Secret (GCCH). However, there may be some limitations or differences in functionality compared to the commercial Azure cloud. One known limitation is that dynamic memberships for administrative units are not currently supported in Azure Government for Microsoft 365 groups. Additionally, some features may not be available in Azure Government or GCCH due to compliance or regulatory requirements.

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@J227668 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
