### ISSUE TITLE
Delegate account required

### ISSUE THREAD

**Issue by DandamanAUS** [MicrosoftDocs/entra-docs#688]
When using AWS Organisations its worth mentioning on this page that another account needs to be delegated as the Identity Center Administration account and the IAM Identity Center is to be enabled on it and the Entra ID SSO setup with that account and not the root management account. 
You might know this but those new to setting it up and following the tutorial for the first time will not.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8e131bf-99d7-a850-a597-ac02b9f6c3a9
* Version Independent ID: a27625d3-cf35-ffaf-5734-d1a2bbcdd60c
* Content: [Tutorial: Microsoft Entra SSO integration with AWS IAM Identity Center (successor to AWS Single Sign-On) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/aws-single-sign-on-tutorial)
* Content Source: [docs/identity/saas-apps/aws-single-sign-on-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/aws-single-sign-on-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@DandamanAUS 
You are correct that when using AWS Organizations, it is recommended to delegate another account as the Identity Center Administration account and enable the IAM Identity Center on it, instead of using the root management account.

This is because the root management account has full access to all AWS services and resources, which can pose a security risk if it is used as the Identity Center Administration account. By delegating another account and enabling the IAM Identity Center on it, you can limit the scope of access and reduce the risk of unauthorized access to your AWS resources.

We value your suggestion to incorporate this detail within the tutorial. I've delegated this to content author @jeevansd, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@jeevansd
Please review it and update as appropriate.

**Comment by CelesteDG** [comment]
@jeevansd @v-hgampala We are migrating all GitHub issues to ADO as we switch our feedback mechanism to UUF. Please either address the issue, or close and track it in ADO no later than June 10, 2024. Thank you.

**Comment by v-hgampala** [comment]
we are working on the issue, will reflect the changes into the main article soon.
#please-close
