### ISSUE TITLE
Code Not Recognizable

### ISSUE THREAD

**Issue by mirojs** [MicrosoftDocs/entra-docs#725]
[Enter feedback here]
Hello,

These following two lines of code from the PageLayout.jsx file didn't seem to be recognizable from the TypeScript editor and led to rendering failure of the page. And upon removing it, other parts of the page got rendered.

            {props.children}
            <br />

Was it only me who run into the issue? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcc60ca8-b5a7-c272-5fb4-82d9d05966dd
* Version Independent ID: e420d92b-36ea-94db-825e-d696b2e7ec3a
* Content: [Tutorial: Handle authentication flows in a React SPA - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-react-sign-in-configure-authentication)
* Content Source: [docs/external-id/customers/tutorial-single-page-app-react-sign-in-configure-authentication.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-single-page-app-react-sign-in-configure-authentication.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @garrodonnell
* Microsoft Alias: **godonnell**

**Comment by TPavanBalaji** [comment]
@mirojs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@mirojs 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by henrymbuguakiarie** [comment]
Hello @mirojs,

Thanks for your dedication to our documentation. I've moved this issue to an internal work item for tracking. 

I'm going to close this GitHub issue since we are moving away from using GitHub issues, as announced in [Announcing a new way to give feedback on Microsoft Learn](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635). We're working on changes to the article.

#please-close
