### ISSUE TITLE
msidentity-app-sync still based on .NET 5 - either tool should be updated or documentation page

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftDocs/entra-docs#746]
The tool that is used on this page (section Use the Microsoft Identity App Sync Tool), msidentity-app-sync, requires .NET Core 5.0 to be installed.

The page describes that the .NET 7 SDK is required (which is true for the Blazor app). The msidentity-app-sync tool requires the .NET 5 SDK as well.

If the msidentity-app-sync tool is not updated (it was not updated for several years), this documentation should get the configuration values from the Azure portal or using the Azure CLI instead.

Also, I think this page should be updated to .NET 8 - Blazor is different now.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1279b6d-8210-1751-8e37-cf544cd3695d
* Version Independent ID: 6dc2d359-8d50-1df3-7983-29fb06bfdbb6
* Content: [Tutorial - Create a Blazor Server app that uses the Microsoft identity platform for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server)
* Content Source: [docs/identity-platform/tutorial-blazor-server.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-blazor-server.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by PesalaPavan** [comment]
@christiannagel 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@christiannagel 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by henrymbuguakiarie** [comment]
Hello @christiannagel ,

After reviewing the current tutorial, we decided to retire it for the following reason:

- The msidentity-app-sync tool fails to work without .NET 5 installed, and .[NET 5 is no longer supported](https://dotnet.microsoft.com/en-us/platform/support/policy).
- The tutorial uses the blazorserver template to scaffold the code, including calls to Microsoft Graph. However, [.NET 8 discontinued the blazorserver](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#blazorserver).
- The tutorial is based on .NET 7, which is no longer supported.

.NET 8 has a [New Blazor Web App template](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#new-blazor-web-app-template) which  combines the strengths of the existing Blazor Server and Blazor WebAssembly hosting models with the new Blazor capabilities added in .NET 8.

**Solution**

- We need a new tutorial using the [New Blazor Web App template](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#new-blazor-web-app-template). An internal work item will track this, but we have no timeline due to other priorities.

Cc: @AjayBathini-MSFT @PesalaPavan
