### ISSUE TITLE
not working example autopilot

### ISSUE THREAD

**Issue by norbertwell** [MicrosoftDocs/entra-docs#769]
in the dynamics device autpilot old sample cannot work in the future. Should be indicated in an attention-grabbing manner
the change should be indicated for the dynamic device groups rule, the previously used (device.devicePhysicalIds -all _ -notContains "[ZTDID]") will no longer work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7a4070-1be8-5f1f-0092-68fb6b9e2305
* Version Independent ID: cd34312f-b507-affe-555e-1e0c63e7d494
* Content: [Rules for dynamically populated groups membership - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-membership)
* Content Source: [docs/identity/users/groups-dynamic-membership.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-dynamic-membership.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@norbertwell 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @norbertwell 
The issue you mentioned regarding the dynamic device groups rule and the deprecation of the Zero Touch Deployment (ZTD) feature in Intune is not related to the Autopilot feature. The dynamic device groups rule is used to automatically add devices to a group based on certain criteria, while Autopilot is used to automatically set up and configure new devices. 

To clarify, the previously used rule for dynamic device groups, `device.devicePhysicalIds -all _ -notContains "[ZTDID]"`, will no longer work due to the deprecation of the ZTD feature in Intune. Therefore, it is recommended to update the rule for dynamic device groups accordingly. 

I hope this clears up any confusion. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@norbertwell 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
