### ISSUE TITLE
Didn't work ootb 

### ISSUE THREAD

**Issue by whoo** [MicrosoftDocs/entra-docs#809]
I'm trying to update user properties.

```
Connect-MgGraph -Scopes "User.Read.All","User.ReadWrite.All"
Welcome to Microsoft Graph!
Connected via delegated access using xxxx-xxxx-xxxx-xxxx
Readme: https://aka.ms/graph/sdk/powershell
SDK Docs: https://aka.ms/graph/sdk/powershell/docs
API Docs: https://aka.ms/graph/docs
NOTE: You can use the -NoWelcome parameter to suppress this message.
PS > Update-MgUser -UserId 'xxxxxxxxx@xxxxxxxxx.xxx' -MobilePhone "+1XXX XXX XXXX"
Update-MgUser_UpdateExpanded: Insufficient privileges to complete the operation.

Status: 403 (Forbidden)
ErrorCode: Authorization_RequestDenied
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aae83fda-27b9-edca-1b59-1140de4cc3f5
* Version Independent ID: c93eb84b-f04b-de03-f3f5-57d4672b0559
* Content: [Prepopulate contact information for self-service password reset - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-sspr-authenticationdata)
* Content Source: [docs/identity/authentication/howto-sspr-authenticationdata.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-sspr-authenticationdata.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@whoo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@whoo 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
