### ISSUE TITLE
Sender email address and subject line: email and sender are wrong

### ISSUE THREAD

**Issue by jeremyhagan** [MicrosoftDocs/entra-docs#824]
Having just tested this feature, the email I got were from Microsoft Security <MSSecurity-noreply@microsoft.com>
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5a932ce-6046-f6a9-9b85-188c8530174c
* Version Independent ID: 196cb921-fbf8-6819-e0e2-8cd03fda4505
* Content: [Email notifications in Privileged Identity Management (PIM) - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-email-notifications)
* Content Source: [docs/id-governance/privileged-identity-management/pim-email-notifications.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/pim-email-notifications.md)
* Service: **entra-id-governance**
* Sub-service: **privileged-identity-management**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@jeremyhagan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@jeremyhagan you provided, it seems that [MSSecurity-noreply@microsoft.com](mailto:MSSecurity-noreply@microsoft.com) is the email address used by Microsoft Security to send notifications related to security alerts and incidents. If you received an email from this address, it is likely related to a security event or alert that was triggered in your environment.

However, without more information about the specific email you received, it is difficult for me to provide a more detailed answer.

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
