### ISSUE TITLE
Least privelege Entra ID built-in role to `microsoft.aadiam/diagnosticSettings/write`?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/entra-docs#868]
What's the least privelege built-in role to write diagnostic settings, `microsoft.aadiam/diagnosticSettings/write` from <https://portal.azure.com/#view/Microsoft_AAD_IAM/DiagnosticSettingsMenuBlade/~/General>?

* Least privilege role by task: <https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/delegate-by-task>
* Build-in roles: <https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference>

Mentioned docs do not mention this.

[Security Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#security-administrator) could do it in my limited testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f9558c0-abb6-24f8-81c8-9000b80539e8
* Version Independent ID: a4739135-863b-27bb-1f2e-cf297f21b4cc
* Content: [Least privileged roles by task - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/delegate-by-task)
* Content Source: [docs/identity/role-based-access-control/delegate-by-task.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/delegate-by-task.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by PesalaPavan** [comment]
@o-l-a-v 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@rolyon
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@o-l-a-v 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by rolyon** [comment]
Hi @o-l-a-v 
Thanks for your feedback. It looks like this permission is in Azure RBAC instead of Microsoft Entra RBAC.
`microsoft.aadiam/diagnosticSettings/write`
https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/identity#microsoftaadiam

When I search for roles with this permission, I think the Contributor role includes this permission.
https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/general#contributor
![image](https://github.com/MicrosoftDocs/entra-docs/assets/35980532/472e54c2-a964-4d0d-a76e-4dacd3dc05dd)

As an alternative to narrow the permissions, you should be able to create a custom Azure role that includes this permission.
https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-portal

Hopefully this helps.
thanks

**Comment by rolyon** [comment]
#please-close

**Comment by o-l-a-v** [comment]
@rolyon You need Entra ID permissions too, else this would be a way to get access to Entra ID logs with no Entra ID permissions.

**Comment by o-l-a-v** [comment]
@PesalaPavan | @ManoharLakkoju-MSFT | @rolyon 

This documentation request / issue was closed based on a wrong conclusion, please reopen.
