### ISSUE TITLE
Security Question: Custom signing keys for tenant

### ISSUE THREAD

**Issue by govindr-cm** [MicrosoftDocs/entra-docs#890]
I am currently implementing an OpenIDConnect-like flow for Microsoft Entra ID. While investigating this, I ran across the claim that Microsoft allows tenant-specific signing keys ([link to GitHub comment](https://github.com/MicrosoftDocs/azure-docs/issues/38427#issuecomment-545207600)). This made me think of a possible forgery attack if these keys are also allowed to be uploaded by tenant owners. I suspect that Microsoft does not permit some aspects of this attack to happen but I could not find documentation that explicitly addressed the assumptions behind it. Any pointers would be very helpful.

The concern is that tenant owners can create valid OIDC tokens with claims that they do not actually own, and can thus spoof identities.

Let's say I'm the tenant owner of a tenant with tenant_id=XYZ.

- Is it possible to upload a custom signing key so that it appears at https://login.microsoftonline.com/XYZ/discovery/v2.0/keys?

If so, then what prevents the following attack?
I create a custom set of claims to spoof a user from tenant ABC (perhaps I have an expired ID token from them) with the issuer URL as my tenanted issuer URL (https://login.microsoftonline.com/XYZ/v2.0/), update the expiration time, and sign the token with my custom key. Now I can present this token to a multitenant application - the signature will validate and the claims are valid - and I will successfully authenticate as a user from tenant ABC.

Again I believe I'm missing something basic, probably some documentation on what kinds of tenant-specific signing keys are allowed, but feel uncomfortable with using tenanted issuer URLs to validate signatures for multitenant applications until I understand what prevents this forgery. Appreciate any pointers and help!

A related, broader question: Is there some page where all the deviations from OIDC spec due to tenants are listed? E.g. [the common tenant discovery doc is not OIDC-compatible](https://github.com/MicrosoftDocs/azure-docs/issues/38427)) And/or is there some place where the security of these deviations is established?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9abce49-5b87-65cf-8ef5-d3421619d535
* Version Independent ID: 25c74f8d-9265-cb29-a80c-eaff4cfc6ec3
* Content: [OAuth 2.0 and OpenID Connect protocols on the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols)
* Content Source: [docs/identity-platform/v2-protocols.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-protocols.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by PesalaPavan** [comment]
@govindr-cm 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by govindr-cm** [comment]
Thank you! Let me know if anything is unclear and you'd like me to elaborate.

**Comment by AjayBathini-MSFT** [comment]
@govindr-cm 
Thank you for your feedback! 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
