### ISSUE TITLE
Finding this article from search

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/entra-docs#892]
I am unsure if it's possible to make this article more searchable. Bing was unable to find it, as was Bing AI searching for 

exchange teams "conditional access" calendar "overlap" sharepoint online

I had to go to Google and specifically search:
site:learn.microsoft.com teams "conditional access" "sharepoint online"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7834fc25-6e4d-1a00-e9d3-949928ccb94b
* Version Independent ID: 23e71a83-28ea-da6f-0e3e-cda56a320358
* Content: [Conditional Access service dependencies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/service-dependencies)
* Content Source: [docs/identity/conditional-access/service-dependencies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/service-dependencies.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@wUEZRs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@wUEZRs Based on your query, it seems like you are looking for information on how to configure Conditional Access policies for Exchange, Teams, and SharePoint Online in Azure.

To configure Conditional Access policies for these services, you can follow the steps below:

Sign in to the Azure portal as a Conditional Access Administrator, Security Administrator, or Global Administrator.
Browse to Azure Active Directory > Security > Conditional Access.
Select New policy.
Give your policy a name and under Assignments, select Users or workload identities.
Under Cloud apps or actions > Include, select Select apps.
Under Select, select the following applications supported by the preview:
Office 365 Exchange Online
Office 365 SharePoint Online
Microsoft Teams
You can then configure the policy settings based on your requirements.

Also, the link you provided contains information on service dependencies for Conditional Access policies in Azure. It explains how some services are dependent on others and how to configure policies accordingly.

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by wUEZRs** [comment]
No, that is not my issue at all. Please read the text I put in. It's about searchability/SEO of this article

**Comment by SaibabaBalapur-MSFT** [comment]
@wUEZRs 
Sorry for inconvenience, I'm going to assign this to the document author so they can take a look at it accordingly.

@MicrosoftGuyJFlo
Can you please check and add your comments on this doc update request as applicable.

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for your feedback. I will continue to try to find ways to better present the information as I make updates. 

#please-close
