### ISSUE TITLE
Authenticator on Mac OS

### ISSUE THREAD

**Issue by mrooneyvt** [MicrosoftDocs/entra-docs#90]
This method of getting 2FA on Mac OS is too complicated to remember. What prevents Microsoft from making the Authenticator app on Mac OS?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 465a721b-4702-fd4c-953e-cc6fde14de5e
* Version Independent ID: 7a16f182-99dc-a125-0b42-e1185e533667
* Content: [Configure SSO on macOS and iOS - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-macos-ios)
* Content Source: [docs/identity-platform/single-sign-on-macos-ios.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/single-sign-on-macos-ios.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by ManoharLakkoju-MSFT** [comment]
@mrooneyvt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@mrooneyvt 

Microsoft Authenticator app is available for Mac OS. You can download it from the Mac App Store. Once you have installed the app, you can follow the instructions in the documentation to set up 2FA for your Microsoft account on Mac OS using the Authenticator app.

Regarding your question about why Microsoft did not develop the Authenticator app for Mac OS earlier, I cannot speak to the specific reasons. However, it is possible that the development of the app was prioritized based on user demand and feedback.

I hope this information helps. Let me know if you have any further questions or concerns.

**Comment by mrooneyvt** [comment]
Hi Ajay,

I cannot find any Microsoft Authenticator products in the Mac Applestore. 

Was it developed by someone or some entity not Microsoft?
 
Regards,
..michael..
Michael Rooney
3047 Centerville Road
Hyde Park VT 05655
***@***.***

**Comment by AjayBathini-MSFT** [comment]
@mrooneyvt 

You are correct that the Microsoft Authenticator app is not currently available on the Mac App Store.

The Microsoft Authenticator app is developed and maintained by Microsoft, and it is available for download on mobile devices running iOS and Android. However, it is not currently available for Mac OS.

The process of setting up 2FA on Mac OS using the Microsoft Authenticator app that I mentioned earlier may have been referring to using the app on a mobile device to set up 2FA for a Microsoft account, which can then be used to sign in to Microsoft services on a Mac OS device.

I understand that the process of setting up 2FA on Mac OS using the Microsoft Authenticator app may seem complicated. While I cannot speak for Microsoft's decision-making process, I can provide some possible reasons why the Authenticator app may not be available on Mac OS.

One reason could be that Mac OS has its own built-in 2FA system called Two-Factor Authentication, which is integrated with Apple's iCloud Keychain. This system provides an extra layer of security for Apple ID accounts and can be used to secure other Apple services as well. Microsoft may have decided that it is not necessary to develop a separate Authenticator app for Mac OS since the built-in 2FA system already provides similar functionality.

Another reason could be that Microsoft may have prioritized developing the Authenticator app for other platforms, such as iOS and Android, which have a larger user base and are more commonly used for accessing Microsoft services. Developing and maintaining an app for multiple platforms can be time-consuming and resource-intensive, and Microsoft may have decided to focus on the platforms that are most widely used by its customers.

That being said, it is always possible that Microsoft may decide to develop an Authenticator app for Mac OS in the future if there is sufficient demand from its customers.

**Comment by mrooneyvt** [comment]
Thank you Ajay,

Your explanation makes sense. Now if everyone else would only go along with it. 

There is something further that Mac OS can do easily which is to send and receive encrypted emails. That is pretty secure at least until organic computers are in everyone’s hands at which point probably only physical analysis will work. 
 
Regards,
..michael..
Michael Rooney
3047 Centerville Road
Hyde Park VT 05655
***@***.***
