### ISSUE TITLE
Known limitations text is unclear

### ISSUE THREAD

**Issue by IanT-UofT** [MicrosoftDocs/entra-docs#913]
The wording of the known limitations text is unclear.  Are sign-in frequency controls respected when a conditional access policy also includes a custom control?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e03d33c6-c60b-153c-bf76-a127be502170
* Version Independent ID: 7bbf1dc5-bd91-d03a-7939-439bfbee85c9
* Content: [Custom controls in Microsoft Entra Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/controls#known-limitations)
* Content Source: [docs/identity/conditional-access/controls.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/controls.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@IanT-UofT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@IanT-UofT 

Yes, sign-in frequency controls are respected when a conditional access policy also includes a custom control.

The known limitations text in the documentation likely refers to potential limitations with custom controls themselves, not their interaction with sign-in frequency.

Here's a breakdown:

Sign-in frequency controls: This is a built-in Azure AD Conditional Access feature that defines how often a user needs to re-authenticate based on specific settings.
Custom controls: These are integrations with third-party identity providers or security solutions that extend the capabilities of Conditional Access policies.
Since sign-in frequency controls are a core feature of Conditional Access, they work independently of any custom controls included in the same policy.

Here are some additional points to consider:

The order of policies might affect the evaluation. If a policy with sign-in frequency control is evaluated before a policy with a custom control, the sign-in frequency will be applied first.
Custom controls might introduce additional authentication steps, but they shouldn't interfere with the enforcement of sign-in frequency settings.
Here are some resources for further clarification:

Microsoft Entra documentation on Conditional Access session controls: https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-session (This page might not explicitly mention custom controls, but it explains session controls which include sign-in frequency)
Microsoft Entra documentation on custom controls: https://learn.microsoft.com/en-us/entra/identity/conditional-access/controls
