### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by zameb** [MicrosoftDocs/entra-docs#99]
It says: For the Redirect URIs enter http://localhost:3000

But https values are required to enable the "save" button.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12739084-4ac9-6850-9be5-88877a28e4b2
* Version Independent ID: b0f5fb6b-ae55-22aa-6a53-972c52212d6f
* Content: [Tutorial: Register a Single-page application with the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-single-page-app-react-register-app)
* Content Source: [docs/identity-platform/tutorial-single-page-app-react-register-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-single-page-app-react-register-app.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by ManoharLakkoju-MSFT** [comment]
@zameb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@zameb 
You are correct that the tutorial mentions using `http://localhost:3000` as the Redirect URI for a single-page app with React. However, as you mentioned, the Microsoft identity platform requires the use of `https` for security reasons. Therefore, you need to use `https` values for your Redirect URIs instead of `http` to enable the "save" button. 

To use `https` values for your Redirect URIs, you can use a tool like ngrok to create a secure tunnel to your local development environment. This will allow you to use a `https` URL for your Redirect URI. You can find more information on how to use ngrok in the tutorial you mentioned.

**Comment by ManoharLakkoju-MSFT** [comment]
@zameb 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
